spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routers:
        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/**
        - id: account-ws
          uri: lb://account-ws
          predicates:
            - Path=/account-ws/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8010/eureka
    instance:
      hostname: localhost

server:
  post: 8012
